-- 0005_validation.sql
-- Trade validation / verification. Three things get checked, and all three
-- land in the same run+checks shape so the UI renders one component:
--
--   connectivity   -- can we reach the provider from THIS host, with THESE keys
--   preflight      -- would this specific order actually be accepted right now
--   reconciliation -- does freqtrade's idea of a trade match the exchange's

create table if not exists public.validation_runs (
  id             uuid primary key default gen_random_uuid(),
  owner_id       uuid references public.profiles (id) on delete cascade,
  account_id     uuid references public.exchange_accounts (id) on delete cascade,
  bot_instance_id uuid references public.bot_instances (id) on delete set null,
  kind           public.validation_kind not null,
  status         public.check_status not null default 'skipped',
  -- Where the run executed. A KuCoin connectivity result is only meaningful
  -- alongside the egress region it was measured from.
  host           text,
  egress_ip      text,
  egress_region  text,
  provider       text,
  checks_total   integer not null default 0,
  checks_passed  integer not null default 0,
  checks_warning integer not null default 0,
  checks_failed  integer not null default 0,
  summary        text,
  context        jsonb not null default '{}'::jsonb,
  started_at     timestamptz not null default now(),
  finished_at    timestamptz,
  duration_ms    integer,
  created_at     timestamptz not null default now()
);

create index if not exists validation_runs_owner_idx on public.validation_runs (owner_id, created_at desc);
create index if not exists validation_runs_account_idx on public.validation_runs (account_id, created_at desc);
create index if not exists validation_runs_kind_idx on public.validation_runs (kind, status, created_at desc);

create table if not exists public.validation_checks (
  id          bigint generated by default as identity primary key,
  run_id      uuid not null references public.validation_runs (id) on delete cascade,
  code        text not null,                       -- stable machine key, e.g. 'kucoin.geo_block'
  title       text not null,
  status      public.check_status not null,
  severity    public.check_severity not null default 'warning',
  pair        text,
  message     text,
  -- What we wanted vs what we saw. Kept as jsonb because the shape differs per
  -- check (a balance check compares numbers, a permission check compares sets).
  expected    jsonb,
  actual      jsonb,
  remediation text,
  duration_ms integer,
  created_at  timestamptz not null default now()
);

create index if not exists validation_checks_run_idx on public.validation_checks (run_id);
create index if not exists validation_checks_failed_idx
  on public.validation_checks (code, created_at desc) where status in ('failed', 'error');

comment on column public.validation_checks.remediation is
  'Operator-facing fix. Populated for known failures, e.g. the KuCoin US geo-block telling you to redeploy in a non-US region.';

-- ---------------------------------------------------------------------------
-- order_reconciliations: freqtrade's record vs the exchange's record
-- ---------------------------------------------------------------------------
create table if not exists public.order_reconciliations (
  id                 bigint generated by default as identity primary key,
  run_id             uuid references public.validation_runs (id) on delete cascade,
  bot_instance_id    uuid references public.bot_instances (id) on delete set null,
  account_id         uuid references public.exchange_accounts (id) on delete set null,
  pair               text not null,
  side               text,
  ft_trade_id        bigint,
  ft_order_id        text,
  exchange_order_id  text,
  ft_amount          numeric(38, 18),
  exchange_amount    numeric(38, 18),
  amount_delta       numeric(38, 18),
  ft_price           numeric(38, 18),
  exchange_price     numeric(38, 18),
  price_delta        numeric(38, 18),
  ft_cost            numeric(38, 18),
  exchange_cost      numeric(38, 18),
  ft_fee             numeric(38, 18),
  exchange_fee       numeric(38, 18),
  fee_currency       text,
  ft_status          text,
  exchange_status    text,
  matched            boolean not null default false,
  discrepancy_pct    numeric(18, 8),
  discrepancy_kind   text,                          -- 'missing_on_exchange' | 'missing_in_bot' | 'amount' | 'price' | 'fee' | 'status'
  notes              text,
  checked_at         timestamptz not null default now()
);

create index if not exists order_reconciliations_run_idx on public.order_reconciliations (run_id);
create index if not exists order_reconciliations_unmatched_idx
  on public.order_reconciliations (bot_instance_id, checked_at desc) where not matched;
