-- 0006_live_trading.sql
-- Live trading data. Two distinct things live here:
--
--   1. Views over the bot's own schema, so the app can read live state without
--      keeping a second copy. Created lazily, because those tables do not exist
--      until freqtrade has connected once and run its own migrations.
--   2. trade_archive + balance_snapshots, which are OURS. They survive a
--      freqtrade schema reset, a bot redeploy, or a switch of exchange.
--
-- The bot's schema is named per bot instance (default ft_main) rather than
-- hardcoded. That is the seam that makes a second bot a row insert instead of a
-- migration: bot #2 gets ft_<its id>, connects with a different search_path, and
-- nothing here changes.

create schema if not exists ft_main;

comment on schema ft_main is
  'Tables created and owned by the default freqtrade process. Never edit by hand.';

-- 0001 created a schema called `freqtrade` before the per-bot naming was settled.
-- Drop it if it is still empty so there is exactly one convention.
do $$
begin
  if to_regnamespace('freqtrade') is not null
     and not exists (select 1 from pg_class c
                      join pg_namespace n on n.oid = c.relnamespace
                     where n.nspname = 'freqtrade') then
    drop schema freqtrade;
  end if;
end $$;

alter table public.bot_instances
  add column if not exists db_schema text not null default 'ft_main';

comment on column public.bot_instances.db_schema is
  'Postgres schema holding this bot''s freqtrade tables. The bot connects with search_path set to it.';

create table if not exists public.trade_archive (
  id                bigint generated by default as identity primary key,
  bot_instance_id   uuid references public.bot_instances (id) on delete cascade,
  owner_id          uuid references public.profiles (id) on delete cascade,
  ft_trade_id       bigint not null,
  pair              text not null,
  base_currency     text,
  quote_currency    text,
  exchange          text,
  strategy          text,
  timeframe         text,
  is_short          boolean not null default false,
  is_open           boolean not null default false,
  amount            numeric(38, 18),
  stake_amount      numeric(38, 18),
  open_rate         numeric(38, 18),
  close_rate        numeric(38, 18),
  open_date         timestamptz,
  close_date        timestamptz,
  close_profit_abs  numeric(38, 18),
  close_profit_pct  numeric(18, 8),
  realized_profit   numeric(38, 18),
  fee_open          numeric(18, 10),
  fee_close         numeric(18, 10),
  enter_tag         text,
  exit_reason       text,
  leverage          numeric(18, 8),
  trading_mode      public.trading_mode not null default 'live',
  raw               jsonb not null default '{}'::jsonb,
  synced_at         timestamptz not null default now(),
  constraint trade_archive_unique unique (bot_instance_id, ft_trade_id)
);

create index if not exists trade_archive_owner_idx on public.trade_archive (owner_id, close_date desc nulls first);
create index if not exists trade_archive_open_idx on public.trade_archive (bot_instance_id) where is_open;
create index if not exists trade_archive_pair_idx on public.trade_archive (pair, close_date desc);

create table if not exists public.balance_snapshots (
  id             bigint generated by default as identity primary key,
  owner_id       uuid references public.profiles (id) on delete cascade,
  account_id     uuid references public.exchange_accounts (id) on delete cascade,
  bot_instance_id uuid references public.bot_instances (id) on delete set null,
  captured_at    timestamptz not null default now(),
  currency       text not null,
  free           numeric(38, 18) not null default 0,
  used           numeric(38, 18) not null default 0,
  total          numeric(38, 18) not null default 0,
  valuation_currency text,
  valuation      numeric(38, 18),
  source         text not null default 'exchange'
);

create index if not exists balance_snapshots_account_idx
  on public.balance_snapshots (account_id, captured_at desc);
create index if not exists balance_snapshots_currency_idx
  on public.balance_snapshots (account_id, currency, captured_at desc);

-- ---------------------------------------------------------------------------
-- Lazy views over the bot's own tables
-- ---------------------------------------------------------------------------
-- freqtrade creates its tables on first connect, which is after this migration
-- runs. So instead of defining the views statically, expose a function the app
-- calls once the bot is up. Idempotent; safe to call on every boot.
create or replace function public.refresh_freqtrade_views(p_schema text default 'ft_main')
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  created text[] := '{}';
  ident   text;
begin
  -- p_schema reaches format() as an identifier, but it arrives from the caller,
  -- so validate its shape before it is ever interpolated.
  if p_schema !~ '^[a-z_][a-z0-9_]{0,62}$' then
    raise exception 'invalid schema name: %', p_schema;
  end if;
  ident := quote_ident(p_schema);

  if to_regclass(ident || '.trades') is not null then
    execute format($v$
      create or replace view public.v_live_trades
      with (security_invoker = on) as
      select t.id            as ft_trade_id,
             t.pair,
             t.base_currency,
             t.stake_currency as quote_currency,
             t.exchange,
             t.strategy,
             t.timeframe,
             t.is_open,
             coalesce(t.is_short, false) as is_short,
             t.amount,
             t.stake_amount,
             t.open_rate,
             t.close_rate,
             t.open_date,
             t.close_date,
             t.close_profit      as close_profit_pct,
             t.close_profit_abs,
             t.realized_profit,
             t.fee_open,
             t.fee_close,
             t.enter_tag,
             t.exit_reason,
             t.leverage
        from %s.trades t
    $v$, ident);
    created := created || 'v_live_trades';
  end if;

  if to_regclass(ident || '.orders') is not null then
    execute format($v$
      create or replace view public.v_live_orders
      with (security_invoker = on) as
      select o.id             as ft_order_id,
             o.ft_trade_id,
             o.ft_pair        as pair,
             o.order_id       as exchange_order_id,
             o.status,
             o.side,
             o.order_type,
             o.price,
             o.average,
             o.amount,
             o.filled,
             o.remaining,
             o.cost,
             o.order_date,
             o.order_filled_date,
             o.ft_is_open
        from %s.orders o
    $v$, ident);
    created := created || 'v_live_orders';
  end if;

  if cardinality(created) = 0 then
    return format('no freqtrade tables in schema %s yet; no views created', p_schema);
  end if;

  return 'created/refreshed: ' || array_to_string(created, ', ');
end;
$$;

comment on function public.refresh_freqtrade_views(text) is
  'Creates public.v_live_trades / v_live_orders over a bot schema once freqtrade has created its tables. Idempotent; call on every boot.';
