-- 0012_platform_hardening.sql
-- Hardening appropriate to a trading platform that is reachable from the
-- internet. The linter findings were the floor, not the ceiling.
--
-- Threat model this addresses: an attacker who has obtained a valid signed-in
-- session (stolen JWT, compromised browser, malicious user) and is now poking
-- at the API to escalate, exfiltrate credentials, or move funds.

-- ---------------------------------------------------------------------------
-- 1. Make it structurally impossible to store a live API key
-- ---------------------------------------------------------------------------
-- exchange_accounts holds the NAME of the env var, never the secret. Nothing
-- stops a careless caller pasting the key itself into that column, at which
-- point a database leak becomes a funds leak. Constrain the shape so only a
-- shell-style env var name fits: uppercase, digits, underscores.
alter table public.exchange_accounts
  drop constraint if exists exchange_accounts_env_var_shape;
alter table public.exchange_accounts
  add constraint exchange_accounts_env_var_shape check (
        (api_key_env_var      is null or api_key_env_var      ~ '^[A-Z][A-Z0-9_]{1,63}$')
    and (api_secret_env_var   is null or api_secret_env_var   ~ '^[A-Z][A-Z0-9_]{1,63}$')
    and (api_password_env_var is null or api_password_env_var ~ '^[A-Z][A-Z0-9_]{1,63}$')
  );

-- Same reasoning for the fingerprint: it must be a sha256 hex digest, so a raw
-- key cannot be parked there either.
alter table public.exchange_accounts
  drop constraint if exists exchange_accounts_fingerprint_shape;
alter table public.exchange_accounts
  add constraint exchange_accounts_fingerprint_shape check (
    api_key_fingerprint is null or api_key_fingerprint ~ '^[0-9a-f]{64}$'
  );

comment on constraint exchange_accounts_env_var_shape on public.exchange_accounts is
  'Only env var NAMES belong here. The shape check makes pasting a live secret into the row fail loudly.';

-- ---------------------------------------------------------------------------
-- 2. No object creation in the API schema by API roles
-- ---------------------------------------------------------------------------
-- Postgres grants CREATE on public to PUBLIC by default. A signed-in user
-- should never be able to add a table, function or type to the schema PostgREST
-- serves.
revoke create on schema public from public;
revoke create on schema public from anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Audit trail for the actions that move money or change trust
-- ---------------------------------------------------------------------------
create table if not exists public.security_events (
  id          bigint generated by default as identity primary key,
  owner_id    uuid references public.profiles (id) on delete set null,
  actor       text,                       -- db role that made the change
  event       text not null,              -- 'account.created', 'account.key_rotated', ...
  entity      text not null,              -- table name
  entity_id   text,
  before      jsonb,
  after       jsonb,
  at          timestamptz not null default now()
);

create index if not exists security_events_owner_idx on public.security_events (owner_id, at desc);
create index if not exists security_events_event_idx on public.security_events (event, at desc);

alter table public.security_events enable row level security;
alter table public.security_events force row level security;

-- Read your own history. Nobody writes through the API -- only the trigger does.
drop policy if exists security_events_read_own on public.security_events;
create policy security_events_read_own on public.security_events
  for select to authenticated
  using (owner_id = public.current_profile_id());

revoke all on public.security_events from anon, authenticated;
grant select on public.security_events to authenticated;

create or replace function public.audit_security_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  ev text;
  owner uuid;
  before_j jsonb;
  after_j  jsonb;
begin
  if tg_op = 'INSERT' then
    ev := tg_argv[0] || '.created';
    after_j := to_jsonb(new);
    owner := new.owner_id;
  elsif tg_op = 'UPDATE' then
    ev := tg_argv[0] || '.updated';
    before_j := to_jsonb(old);
    after_j := to_jsonb(new);
    owner := new.owner_id;
  else
    ev := tg_argv[0] || '.deleted';
    before_j := to_jsonb(old);
    owner := old.owner_id;
  end if;

  -- Credential rotation is worth its own event name; it is the one change that
  -- silently repoints a bot at a different exchange identity.
  if tg_op = 'UPDATE' and tg_argv[0] = 'account'
     and (new.api_key_fingerprint is distinct from old.api_key_fingerprint
          or new.api_key_env_var is distinct from old.api_key_env_var) then
    ev := 'account.key_rotated';
  end if;

  insert into public.security_events (owner_id, actor, event, entity, entity_id, before, after)
  values (owner, current_user, ev, tg_table_name,
          coalesce(new.id, old.id)::text, before_j, after_j);

  return coalesce(new, old);
end;
$$;

revoke all on function public.audit_security_event() from public, anon, authenticated;

drop trigger if exists exchange_accounts_audit on public.exchange_accounts;
create trigger exchange_accounts_audit
  after insert or update or delete on public.exchange_accounts
  for each row execute function public.audit_security_event('account');

drop trigger if exists bot_instances_audit on public.bot_instances;
create trigger bot_instances_audit
  after insert or update or delete on public.bot_instances
  for each row execute function public.audit_security_event('bot');

-- ---------------------------------------------------------------------------
-- 4. Cap what one account can queue
-- ---------------------------------------------------------------------------
-- profiles.max_concurrent_backtests existed but nothing enforced it. A signed-in
-- user could otherwise queue unbounded jobs and starve the worker.
create or replace function public.enforce_backtest_quota()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  running int;
  cap     int;
begin
  select coalesce(max_concurrent_backtests, 2) into cap
    from public.profiles where id = new.owner_id;

  if cap is null then
    return new;
  end if;

  select count(*) into running
    from public.backtest_jobs
   where owner_id = new.owner_id
     and status in ('queued', 'running');

  if running >= cap then
    raise exception 'backtest quota reached: % job(s) already queued or running (limit %)', running, cap
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_backtest_quota() from public, anon, authenticated;

drop trigger if exists backtest_jobs_quota on public.backtest_jobs;
create trigger backtest_jobs_quota
  before insert on public.backtest_jobs
  for each row execute function public.enforce_backtest_quota();
