-- The third column: what the strategy said, before anything got in the way.
--
-- Verification so far has compared two records -- the bot's orders against the
-- exchange's fills -- which answers "did what the bot instructed actually
-- happen". It cannot answer the question before that one: did the bot instruct
-- what the strategy called for?
--
-- The gap between them is real and invisible today. A strategy can signal an
-- entry the bot never acts on because every slot is full, the stake is not
-- there, the pair is locked after a loss, or the bot was mid-deploy. None of
-- those leave an order, so nothing downstream ever sees them, and a strategy
-- that "isn't trading" looks identical to one that has nothing to say.
--
-- signal_source distinguishes where a signal came from. 'bot' is the running
-- strategy's own dataframe -- the same columns the candle chart draws its
-- triangles from. 'tradingview' is an independently written Pine version
-- reporting through a webhook, which is a second opinion rather than a truth:
-- when it disagrees, two implementations differ and someone has to look.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'signal_source') then
    create type public.signal_source as enum ('bot', 'tradingview', 'replay');
  end if;
end $$;

create table if not exists public.strategy_signals (
  id               bigint generated by default as identity primary key,
  owner_id         uuid references public.profiles (id) on delete cascade,
  bot_instance_id  uuid references public.bot_instances (id) on delete set null,
  source           public.signal_source not null default 'bot',
  strategy         text,
  exchange         text,
  pair             text not null,
  timeframe        text not null,
  side             text not null,          -- enter_long / exit_long / enter_short / exit_short
  -- The candle the signal belongs to, not when we noticed it. Two sources agree
  -- only if they agree about the same bar, and the bot may record a bar minutes
  -- after it closed.
  bar_time         timestamptz not null,
  price            numeric(38, 18),
  payload          jsonb not null default '{}'::jsonb,
  received_at      timestamptz not null default now(),

  -- The same bar cannot signal the same way twice from one source. This is what
  -- makes both capture paths safe to retry: the bot re-reads a dataframe that
  -- overlaps what it already stored, and TradingView resends alerts.
  constraint strategy_signals_unique
    unique (bot_instance_id, source, pair, timeframe, side, bar_time)
);

create index if not exists strategy_signals_lookup_idx
  on public.strategy_signals (bot_instance_id, pair, bar_time desc);
create index if not exists strategy_signals_owner_idx
  on public.strategy_signals (owner_id, received_at desc);

alter table public.strategy_signals enable row level security;
alter table public.strategy_signals force row level security;

drop policy if exists strategy_signals_owner_read on public.strategy_signals;
create policy strategy_signals_owner_read on public.strategy_signals
  for select using (owner_id = auth.uid());

-- Writes come from the bot's service-role client and from the webhook receiver,
-- both of which bypass RLS. No policy grants insert to a signed-in user: a
-- dashboard that could invent signals could hide a missed trade.

grant select on public.strategy_signals to authenticated;
grant select, insert, update, delete on public.strategy_signals to service_role;
grant usage, select on sequence public.strategy_signals_id_seq to service_role;
