-- Which strategy was running, on which bot, between when and when.
--
-- freqtrade already stamps every trade with a strategy name, and that carries
-- most of the weight. It has two gaps this closes.
--
-- The first is edits. A strategy iterated on in place keeps its class name, so
-- "TrendPullbackStrategy" in July and "TrendPullbackStrategy" in September can
-- be materially different code and the trade rows cannot tell them apart. A
-- source fingerprint can.
--
-- The second is everything that is not a trade. Signals, balance snapshots,
-- validation runs and drawdown all happen under a strategy too, and none of
-- them carry the name. With a start and end time, anything timestamped can be
-- attributed by asking which deployment covered that moment.
--
-- Rows are opened by the bot when it boots and closed when it notices the
-- strategy or its fingerprint has changed. One open row per bot at a time.

create table if not exists public.strategy_deployments (
  id               bigint generated by default as identity primary key,
  owner_id         uuid references public.profiles (id) on delete cascade,
  bot_instance_id  uuid not null references public.bot_instances (id) on delete cascade,
  strategy         text not null,
  -- sha256 of the strategy file. The thing that distinguishes an edit from a
  -- rename, which the name alone cannot.
  source_sha       text,
  timeframe        text,
  stake_amount     numeric(38, 18),
  max_open_trades  integer,
  trading_mode     text,
  started_at       timestamptz not null default now(),
  ended_at         timestamptz,
  notes            text
);

-- At most one open deployment per bot. Without this a crash mid-rotation, or
-- two boots racing, leaves two open rows and every attribution afterwards is
-- ambiguous.
create unique index if not exists strategy_deployments_one_open_per_bot
  on public.strategy_deployments (bot_instance_id) where ended_at is null;

create index if not exists strategy_deployments_window_idx
  on public.strategy_deployments (bot_instance_id, started_at desc);

alter table public.strategy_deployments enable row level security;
alter table public.strategy_deployments force row level security;

drop policy if exists strategy_deployments_owner_read on public.strategy_deployments;
create policy strategy_deployments_owner_read on public.strategy_deployments
  for select using (owner_id = auth.uid());

grant select on public.strategy_deployments to authenticated;
grant select, insert, update, delete on public.strategy_deployments to service_role;
grant usage, select on sequence public.strategy_deployments_id_seq to service_role;

-- Every trade with the deployment that was live when it opened, so the two
-- answers can be compared. They should agree; where they do not, either a trade
-- outlived a strategy change or the stamp is wrong, and both are worth seeing.
create or replace view public.v_trade_strategy
with (security_invoker = on) as
select t.bot_instance_id,
       t.ft_trade_id,
       t.pair,
       t.open_date,
       t.close_date,
       t.close_profit_abs,
       t.strategy                         as stamped_strategy,
       d.strategy                         as deployed_strategy,
       d.source_sha,
       d.id                               as deployment_id,
       (t.strategy is distinct from d.strategy) as disagrees
  from public.trade_archive t
  left join public.strategy_deployments d
    on d.bot_instance_id = t.bot_instance_id
   and t.open_date >= d.started_at
   and (d.ended_at is null or t.open_date < d.ended_at);

grant select on public.v_trade_strategy to authenticated, service_role;
