-- When the bot stopped, for how long, and whether anyone was told.
--
-- v_bot_health has always been able to say a bot is offline. Nothing ever read
-- it. The bot died on 31 August and again on 4 September, recovered both times,
-- and the first anyone knew was days later going looking -- which is the wrong
-- way to find out that a process trading real money was not running.
--
-- An incident opens when the watchdog first sees a bot it expects to be trading
-- go quiet, and closes when it comes back. Two things fall out of that which a
-- heartbeat column alone cannot give: how long it was actually down, and a
-- record afterwards that "did it crash overnight" can be answered from.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'incident_kind') then
    create type public.incident_kind as enum ('offline', 'stale', 'not_trading');
  end if;
end $$;

create table if not exists public.bot_incidents (
  id               bigint generated by default as identity primary key,
  owner_id         uuid references public.profiles (id) on delete cascade,
  bot_instance_id  uuid not null references public.bot_instances (id) on delete cascade,
  kind             public.incident_kind not null,
  detail           text,
  opened_at        timestamptz not null default now(),
  resolved_at      timestamptz,
  -- Filled on resolve so the duration survives even if the clock is questioned
  -- later, and so a query for "worst outage" does not have to recompute it.
  downtime_seconds integer,
  notified         boolean not null default false,
  notify_error     text
);

-- One open incident per bot per kind. Without it every watchdog pass while the
-- bot is down opens another row, and a ten-minute outage reads as forty
-- separate failures.
create unique index if not exists bot_incidents_one_open_per_kind
  on public.bot_incidents (bot_instance_id, kind) where resolved_at is null;

create index if not exists bot_incidents_recent_idx
  on public.bot_incidents (bot_instance_id, opened_at desc);

alter table public.bot_incidents enable row level security;
alter table public.bot_incidents force row level security;

drop policy if exists bot_incidents_owner_read on public.bot_incidents;
create policy bot_incidents_owner_read on public.bot_incidents
  for select using (owner_id = auth.uid());

grant select on public.bot_incidents to authenticated;
grant select, insert, update, delete on public.bot_incidents to service_role;
grant usage, select on sequence public.bot_incidents_id_seq to service_role;
