"""Turn a validated StrategySpec into freqtrade strategy source.

The safety property this module relies on: by the time a spec reaches here it
has been through `spec.parse`, so every column name came out of the catalog and
every operator is one of a fixed set. This module re-checks column names against
a regex anyway -- generation is the last point where a bad identifier could
become executable, and the check costs nothing.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from app.strategy_builder import catalog
from app.strategy_builder.spec import (
    Comparison,
    Constant,
    RuleGroup,
    StrategySpec,
    _OPERATOR_SYMBOL,
)

HEADER = '''"""
{title}

Generated by the strategy builder from a declarative spec -- do not edit by hand.
Edits here are lost the next time the strategy is compiled; change the spec and
recompile instead.

spec version : {spec_version}
spec sha256  : {spec_hash}
"""

from freqtrade.strategy import IStrategy
from pandas import DataFrame
import talib.abstract as ta

try:
    # freqtrade 2024.x moved qtpylib out to the `technical` package.
    from technical import qtpylib
except ImportError:  # pragma: no cover - older freqtrade
    import freqtrade.vendor.qtpylib.indicators as qtpylib

'''


class CodegenError(RuntimeError):
    pass


def _col(name: str) -> str:
    """Render a column reference, re-validating the identifier."""
    if not catalog.COLUMN_RE.match(name):
        raise CodegenError(f"refusing to emit unsafe column reference {name!r}")
    return f"dataframe['{name}']"


def _number(value: float) -> str:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise CodegenError(f"expected a number, got {value!r}")
    # repr keeps float precision without scientific-notation surprises.
    return repr(float(value))


def _comparison(rule: Comparison) -> str:
    left = _col(rule.left)

    if rule.op == "between":
        low, high = rule.right  # validated as a 2-list by the spec
        return f"({left}.between({_number(low)}, {_number(high)}))"

    if isinstance(rule.right, Constant):
        right = _number(rule.right.const)
    elif isinstance(rule.right, str):
        right = _col(rule.right)
    else:
        raise CodegenError(f"unsupported right operand for {rule.op}: {rule.right!r}")

    if rule.op in _OPERATOR_SYMBOL:
        return f"({left} {_OPERATOR_SYMBOL[rule.op]} {right})"

    if rule.op == "crosses_above":
        return f"(qtpylib.crossed_above({left}, {right}))"
    if rule.op == "crosses_below":
        return f"(qtpylib.crossed_below({left}, {right}))"

    raise CodegenError(f"unhandled operator {rule.op!r}")


def render_rule(rule: Any) -> str:
    """Render a rule tree as a pandas boolean expression."""
    if isinstance(rule, Comparison):
        return _comparison(rule)

    if isinstance(rule, RuleGroup):
        children = [render_rule(c) for c in rule.children()]
        if not children:
            raise CodegenError("empty rule group")
        if rule.all is not None:
            return "(" + " & ".join(children) + ")"
        if rule.any is not None:
            return "(" + " | ".join(children) + ")"
        # "not": [a, b] reads as "none of these hold".
        inner = " | ".join(children)
        return f"(~({inner}))"

    raise CodegenError(f"unrecognised rule node {type(rule).__name__}")


def _roi_literal(roi: dict[str, float]) -> str:
    ordered = sorted(roi.items(), key=lambda kv: int(kv[0]))
    lines = [f'        "{k}": {v},' for k, v in ordered]
    return "{\n" + "\n".join(lines) + "\n    }"


def _indicator_block(spec: StrategySpec) -> list[str]:
    lines: list[str] = []
    for indicator in spec.indicators:
        definition = indicator.definition
        lines.append(f"        # {definition.label} ({indicator.kind})")
        for line in definition.emit(indicator.id, indicator.params):
            lines.append(f"        {line}")
        lines.append("")
    if not lines:
        lines.append("        # No indicators declared; rules run on raw OHLCV.")
        lines.append("")
    return lines


def _signal_block(
    spec: StrategySpec, *, which: str
) -> list[str]:
    """Emit populate_entry_trend or populate_exit_trend."""
    is_entry = which == "entry"
    method = "populate_entry_trend" if is_entry else "populate_exit_trend"
    signals = spec.entry if is_entry else spec.exit

    lines = [
        f"    def {method}(self, dataframe: DataFrame, metadata: dict) -> DataFrame:",
    ]

    if signals is None:
        lines += [
            "        # No exit rules in the spec; exits come from ROI, stoploss",
            "        # and the trailing stop configured above.",
            "        return dataframe",
            "",
        ]
        return lines

    emitted = False
    for direction in ("long", "short"):
        rule = getattr(signals, direction)
        if rule is None:
            continue
        expression = render_rule(rule)
        column = f"{'enter' if is_entry else 'exit'}_{direction}"
        tag_column = f"{'enter' if is_entry else 'exit'}_tag"
        tag = f"{which}_{direction}"

        lines.append(f"        # {direction} {which}")
        if is_entry:
            # A candle with no volume did not really trade; freqtrade strategies
            # conventionally refuse to enter on one, and a backtest that ignores
            # this reports fills that could never have happened.
            lines.append("        dataframe.loc[")
            lines.append(f"            {expression}")
            lines.append("            & (dataframe['volume'] > 0),")
            lines.append(f"            ['{column}', '{tag_column}']")
            lines.append(f"        ] = (1, '{tag}')")
        else:
            lines.append("        dataframe.loc[")
            lines.append(f"            {expression},")
            lines.append(f"            ['{column}', '{tag_column}']")
            lines.append(f"        ] = (1, '{tag}')")
        lines.append("")
        emitted = True

    if not emitted:
        lines.append("        return dataframe")
        lines.append("")
        return lines

    lines.append("        return dataframe")
    lines.append("")
    return lines


def spec_hash(spec: StrategySpec) -> str:
    payload = spec.model_dump(mode="json", by_alias=True, exclude_none=True)
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def generate(spec: StrategySpec) -> str:
    """Render the complete strategy module."""
    risk = spec.risk
    trailing = risk.trailing

    title = spec.description or f"{spec.class_name} strategy"
    body = HEADER.format(
        title=title.strip().splitlines()[0][:200],
        spec_version=spec.spec_version,
        spec_hash=spec_hash(spec),
    )

    lines: list[str] = [
        f"class {spec.class_name}(IStrategy):",
        '    """Compiled from a builder spec."""',
        "",
        "    INTERFACE_VERSION = 3",
        "",
        f"    timeframe = {spec.timeframe!r}",
        f"    can_short = {spec.can_short}",
        "",
        f"    minimal_roi = {_roi_literal(risk.minimal_roi)}",
        "",
        f"    stoploss = {risk.stoploss}",
        "",
        f"    trailing_stop = {trailing.enabled}",
    ]

    if trailing.enabled:
        lines += [
            f"    trailing_stop_positive = {trailing.positive}",
            f"    trailing_stop_positive_offset = {trailing.offset}",
            f"    trailing_only_offset_is_reached = {trailing.only_offset_reached}",
        ]

    lines += [
        "",
        f"    process_only_new_candles = {spec.process_only_new_candles}",
        f"    use_exit_signal = {spec.use_exit_signal}",
        "",
        "    # Derived from the slowest indicator in the spec, so the strategy asks",
        "    # for exactly the warm-up it needs.",
        f"    startup_candle_count = {spec.required_startup_candles()}",
        "",
        "    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:",
    ]
    lines += _indicator_block(spec)
    lines += ["        return dataframe", ""]
    lines += _signal_block(spec, which="entry")
    lines += _signal_block(spec, which="exit")

    source = body + "\n".join(lines).rstrip() + "\n"

    # Belt and braces: the generated module must at minimum be valid python.
    import ast

    try:
        ast.parse(source)
    except SyntaxError as exc:  # pragma: no cover - indicates a generator bug
        raise CodegenError(f"generated invalid python: {exc}") from exc

    return source


def code_sha256(source: str) -> str:
    return hashlib.sha256(source.encode("utf-8")).hexdigest()
